/***************************
 *  Images List
 */
function createImagesList() {
    const imgsList = [];
    let updateListener = () => {};
    let currentImgIndex = null;

    return {
        addUpdateListener(el) {
            updateListener = el;
        },

        add(link) {
            imgsList.push(link);
            
            currentImgIndex = imgsList.length - 1;

            updateListener(imgsList, currentImgIndex);
        },

        remove() {
            
            imgsList.splice(currentImgIndex, 1);
            
            if(currentImgIndex === imgsList.length) {
                currentImgIndex--;

                if(currentImgIndex === -1){
                    currentImgIndex = null;
                }
            }

            updateListener(imgsList, currentImgIndex);
        },

        setCurrentImgIndex(i) {
            currentImgIndex = i;
            updateListener(imgsList, currentImgIndex);
        },

        getCurrentImgIndex() {
            return currentImgIndex;
        },
        
        generateExportText() {
            let text = "";

            text += "HERE IS THE LIST OF LINKS TO ALL YOUR IMAGES\n";
            text += "***********************************\n";

            if(imgsList.length === 0) {
                text += "There is no image on your list."
            }
            else {
                imgsList.forEach(l => {
                    text += "   - " + l + "\n";
                });

            }

            text += "**********************************\n";
            text += "This list is generated by Gallery App, developed by Minh Le.\n";
            text += "You can find me at: \n";
            text += "   - https://www.ledminh.dev\n";
            text += "   - https://github.com/ledminh\n";
            text += "   - https://www.linkedin.com/in/ledminh/";
            
            return text;
        }




    }

}




/***************************
 *  inputKeydownHandler
 */ 
const inputPhotos = document.querySelector('#photo-link');

const createImg = (link) => {
    const img = document.createElement('img');
    img.src = link;
    img.alt = "A photo from " + link;

    return img;
}

const createFigcaption = (link) => {
    const figcaption = document.createElement('figcaption');
    figcaption.innerHTML = "This is a photo from <i>" + link + "</i>";

    return figcaption;

}


const createFigure = (img, figcaption) => {
    const figure = document.createElement('figure');

    figure.appendChild(img);
    figure.appendChild(figcaption);

    return figure;
}

const addInputKeydown = (imgsList) => {
    inputPhotos.addEventListener('keydown', (e) => {
        if(e.key === 'Enter'){
            e.preventDefault();
            const link = e.target.value;
            
            imgsList.add(link);
            

            e.target.value = "";
        } 
    });

}

/*******************************
 *  updatePrevNextBtns
 */

function updatePrevNextBtns(list, currentImgIndex) {
    const prevBtn = document.querySelector(".prevBtn");
    const nextBtn = document.querySelector(".nextBtn");
    const prevNextBtns = document.querySelector(".prevNextBtns");

    if(currentImgIndex === null || list.length === 1){
        prevNextBtns.classList.add("invisible");
    }
    else if(currentImgIndex === 0){
        prevBtn.disabled = true;
        nextBtn.disabled = false;
        prevNextBtns.classList.remove("invisible");
    }
    else if(currentImgIndex === list.length - 1){
        prevBtn.disabled = false;
        nextBtn.disabled = true;
        prevNextBtns.classList.remove("invisible");
    }
    else {
        prevBtn.disabled = false;
        nextBtn.disabled = false;
        prevNextBtns.classList.remove("invisible");
    }
}

/*******************************
 *  imagesListListener
 */
const updatePhoto = (list, currentImgIndex) => {
    const photoContainer = document.querySelector(".photo-container");
        
    photoContainer.innerHTML = "";

    list.forEach((link, i) => {
        const img = createImg(link);
        const figcaption = createFigcaption(link);
        const figure = createFigure(img, figcaption);
        
        if(currentImgIndex === i){
            figure.classList.add("visible");
        }

        photoContainer.appendChild(figure);


    });
}

const updateFunctionBtns = (list) => {
    const funcBtns = document.querySelector(".functionBtns");

    if(list.length === 0) {
        funcBtns.classList.add("invisible");
    }
    else {
        funcBtns.classList.remove("invisible");
    }
}

const updateNumBtns = (list, currentImgIndex) => {
    const numBtns = document.querySelector(".numBtns");
    numBtns.innerHTML = "";

    if(list.length === 0){
        numBtns.classList.remove("visible");
    }
    else {
        numBtns.classList.add("visible");
            

        list.forEach((l, i) => {
            const btn = document.createElement("button");

            btn.classList.add("numBtn");
            btn.innerText = i + 1;

            btn.addEventListener('click', (e) => imgsList.setCurrentImgIndex(i));

            if(i === currentImgIndex){
                btn.classList.add("current");
            }

            numBtns.appendChild(btn);


        });
    }
}




const updateListener = (list, currentImgIndex) => {
    updatePhoto(list, currentImgIndex);
    updateNumBtns(list, currentImgIndex);
    updatePrevNextBtns(list, currentImgIndex);
    updateFunctionBtns(list);
}


const addPrevOnClickHandler = (imgsList) => {
    const prevBtn = document.querySelector(".prevBtn");

    prevBtn.onclick = (e) => {
        imgsList.setCurrentImgIndex(imgsList.getCurrentImgIndex() - 1);
    }

}

const addNextOnClickHandler = (imgsList) => {
    const nextBtn = document.querySelector(".nextBtn");

    nextBtn.onclick = (e) => {
        imgsList.setCurrentImgIndex(imgsList.getCurrentImgIndex() + 1);
    }
}


const addDeleteOnClickHandler = (imgsList) => {
    const deleteBtn = document.querySelector(".deleteBtn");

    deleteBtn.onclick  = (e) => {
        imgsList.remove();
    }
}



const addExportOnClickHandler = (imgsList) => {
    const exportBtn = document.querySelector(".exportBtn");
    exportBtn.onclick = (e) => {
        const text = imgsList.generateExportText();
        var myFile = new File([text], "images-list.txt", {type: "text/plain;charset=utf-8"});
        saveAs(myFile);
    }

}

/*******************************
 *  EXECUTION
 */

const imgsList = createImagesList();


imgsList.addUpdateListener(updateListener);


addInputKeydown(imgsList);
addPrevOnClickHandler(imgsList);
addNextOnClickHandler(imgsList);
addDeleteOnClickHandler(imgsList);
addExportOnClickHandler(imgsList);